data:
  extracts_data: "extracts_v8_101x101.h5"
  reference_raster: "landcover_DE_2018_v1_3035_col_cog.tif"
  model_prefix: "model"  # will be appended with e.g. _cnn.h5

precursor:
  n_obs:  # leave empty to consider all observations
  eua_completely_covered: True
  max_dist_urban_proximity: 1000
  sampling_scheme: "random" # one of "simple", "random"
  osm_scaling: "linear" # one of "linear", "log", "sqrt"
  train_val_test_split: [0.7, 0.15, 0.15]
  shuffle: True
  clean_on_read: True
  balance_training: False
  balance_validation: False
  balance_weight_ratio_green_training: 0.3
  balance_weight_ratio_green_validation: 0.3
  classification: False
  n_green_classes: 5
  augment_training_ds: True
  augment_valid_ds: True

model:
  batch_size: 512
  epochs: 10000
  initial_learning_rate: 1e-4
  reduce_on_plateau_patience: 20
  early_stopping_patience: 40
  warmup_epochs: 3
  warmup_lr: 1e-15
  dropout_rate: 0.1
  cnn_model: "greennet" # choose mobilenet or efficientnetb3
  cnn_dense_layers: [15, 10, 5]
  fusion_cnn_neurons: 5
  fusion_ann_neurons: 5
  ann_hidden_layers: 1
  ann_hidden_layer_nodes: [20, 10, 5] # int | list[int]
  ann_bn_or_do: "bn"
  fusion_hidden_layers: 3
  fusion_hidden_layer_nodes: [20, 15, 10, 5]
  greennet_skipconn: True

experiments:
  ann: True
  cnn: True
  fusion: True
  rf: True
  lm: True

output:
  gpkg: True
  h5: False
  prediction:
    extracts_data: "extracts_v8_101x101.h5"

reproducibility:
  seed: 42
  global_determinism: False  # leads to reproducibility even in GPU operations, could be slower
