name: fusion-new
channels:
  - conda-forge
dependencies:
  - dask=2022.9.2
  - geopandas=0.10.2
  - joblib=1.1.0
  - pandas=1.3
  - pip
  - python=3.9.6
  - python-box=5.4
  - rasterio=1.2.10
  - rich
  - scikit-learn=1.0
  - pip:
    - h5py
    - matplotlib==3.4.3
    - numpy==1.22
    - protobuf==3.19
    - seaborn
    - tensorflow==2.8
    - tifffile
  # - cudatoolkit=11.2
  # - cudnn=8.1
  # mamba install cuda -c nvidia
  # mamba install cudnn=8.1 -c nvidia

  # cuda-nvcc from channel -c nvidia for ptxas and nvcc
